name: e_shop
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: ">=2.17.1 <3.0.0"

# Dependencies specify other packages that your package needs in order to work.

dependencies:
  flutter:
    sdk: flutter



  cupertino_icons: ^1.0.2
  firebase_core: ^1.17.1
  google_fonts: ^3.0.1
  firebase_auth: ^3.3.19



dev_dependencies:
  flutter_test:
    sdk: flutter

  
  # rules and activating additional ones.
  flutter_lints: ^2.0.0


flutter:


  uses-material-design: true

assets:
 - assets/images/

  