// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDGdcmiRDwmeR2XNqhZ-FwIfV1ELPZ2T3k',
    appId: '1:731277174155:web:caae0a1e5146141484fb8e',
    messagingSenderId: '731277174155',
    projectId: 'e-shop-1570a',
    authDomain: 'e-shop-1570a.firebaseapp.com',
    storageBucket: 'e-shop-1570a.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBZq3t0jdoEfMXn5Eid0YtfrQ4Jsp0bzUw',
    appId: '1:731277174155:android:63e0c2895938f92084fb8e',
    messagingSenderId: '731277174155',
    projectId: 'e-shop-1570a',
    storageBucket: 'e-shop-1570a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDX7stMI0WTT-EH33QTH7Q91VWDo7QyfHc',
    appId: '1:731277174155:ios:a5bc1e17cb8cdc0984fb8e',
    messagingSenderId: '731277174155',
    projectId: 'e-shop-1570a',
    storageBucket: 'e-shop-1570a.appspot.com',
    iosClientId: '731277174155-4n1slm0uqji2tiqrneodlgahneeb4iop.apps.googleusercontent.com',
    iosBundleId: 'com.example.eShop',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDX7stMI0WTT-EH33QTH7Q91VWDo7QyfHc',
    appId: '1:731277174155:ios:a5bc1e17cb8cdc0984fb8e',
    messagingSenderId: '731277174155',
    projectId: 'e-shop-1570a',
    storageBucket: 'e-shop-1570a.appspot.com',
    iosClientId: '731277174155-4n1slm0uqji2tiqrneodlgahneeb4iop.apps.googleusercontent.com',
    iosBundleId: 'com.example.eShop',
  );
}
